elasticsearch:
  ingress:
    enabled: true
    hosts:
      - host: es.tanzu.blah.cloud
        paths:
        - path: /
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-live
    tls:
    - secretName: elasticsearch-cert
      hosts:
        - es.tanzu.blah.cloud
  # resources:
  #   requests:
  #     cpu: null
  #     memory: null
  #   limits:
  #     cpu: null
  #     memory: null
  # esJavaOpts: "-Xmx1g -Xms1g"
  extraInitContainers:
   - name: file-permissions
     image: busybox
     command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
     volumeMounts:
     - mountPath: /usr/share/elasticsearch/data
       name: elasticsearch-master
     securityContext:
       privileged: true
       runAsUser: 0